# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - oraclejdk11
# используем режим обычного пользователя для сборки проекта.
sudo: false
services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres

test:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      -mailto:ilya.progress@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
